### ISSUE TITLE
Comments/Questions

### ISSUE THREAD

**Issue by tcbrindle** [atomgalaxy/isocpp-template-this#2]
Hi Gašper,

As promised, I've had a read through the paper. I think it's a fantastic idea (even if it might prove a little too revolutionary for the committee). I do have a couple of questions, and while they're not really "issues" I figure this might be a good place for feedback?

 * Would it be reasonable to allow explicitly declaring `this` to be a pointer?

    For example

    ```cpp
    struct foo {
        void bar(foo const* this) {
            // existing code that expects this as a pointer
        }
    };
    ```

    There doesn’t seem to be any reason to disallow this as far as I can see (it just replicates today’s semantics with a different syntax), and it would allow codebases to migrate to consistently using “explicit `this`”-style declarations without changing implementation code.

  * In the `Person::GetName()` example, you say that “U can only deduce to `Person [cv][&|&&]`”. Does this mean that `U` *must* be deduced, or can I specify it at the call site, like a regular function template?

       ``` cpp
        Person p;
        auto n = p.GetName<const Person&>(); // legal?
       ```

* Is `auto&& this` allowed only in lambdas, or for ordinary member functions as well?

* Presumably a virtual function cannot have a templated `this`, but it might be good to explicitly say so

* Declaring cv- or ref-qualified constructors isn't permitted. But it's not clear to me whether `this`-by-value would be permitted for constructors, or what it would mean if it is:

    ```cpp
    struct example {
        example(example this); // legal? If so, what does it do?
    };
    ```

* Not strictly feedback, but reading this paper makes me wish C++ had a built-in alias for "this type", akin to Swift's `Self`. Then I could say

    ```cpp
    struct my_type_with_a_very_long_name {
        void foo(This const& this, int arg);
    };
   ```

    without having to repeat the long type name for every member function. Unfortunately I think the ugly `_This` is the only possible syntax that could work...

Anyway, great work on the paper, I hope you don't mind me asking (perhaps naive?) questions :)

Tristan

**Comment by atomgalaxy** [comment]
Tristan, thanks for all your feedback! I think if you re-read the paper, you will find all your points have now been included and answered in the paper.

The last point is off-topic, so I'm answering it here.

Basically, this paper gives you the option of saying `auto const& this`, which can only ever deduce to `my_type_with_a_very_long_name`, since you aren't giving the user a choice with a concrete template parameter they are able to address. So yay!
